account/urls.py
# импорт метода path для определения маршрутов
# import path method to define routes
from django.urls import path
from django.contrib.auth import views as auth_views
# импорт контроллеров для отправки ответа на запрос пользователя
# import controllers to send a response to a user request
from account.views import *


app_name = 'account'

# пути ведущие к страницам относительно заданного шаблона(запроса пользователя)
# paths leading to pages relative to the given template(user request)
urlpatterns = [
    path('delete-user/done/', UserDeleteDone.as_view(), name='delete_user_done'),  # страница успешного удаления пользователя
    path('delete-user/', UserDelete.as_view(), name='delete_user'),  # страница удаления пользователя
    path('password-change/', PasswordChange.as_view(), name='password_change'),  # страница изменения пароля
    path('edit/', UserEdit.as_view(), name='edit'),  # страница редактирования информации пользователя
    path('register/activate/<str:sign>/', user_activate, name='register_activate'),  # страница активации
    path('register/done/', RegisterDone.as_view(), name='register_done'),  # страница успешной регистрации
    path('register/', Register.as_view(), name='register'),  # страница регистрации
    path('password-reset/complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),  # страница успешной смены пароля
    path('password-reset/confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'),
         name='password_reset_confirm'),  # страница смены пароля
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),  # страница об успешном запросе сброса пароля
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html'),
         name='password_reset'),  # страница сброса пароля
    path('login/', Login.as_view(), name='login'),  # страница входа
    path('logout/', Logout.as_view(), name='logout'),  # страница выхода
    path('', Account.as_view(), name='profile'),  # страница профиля пользователя
]

playroom/urls.py
# импорт метода path для обработки маршрутов
# import the path method to handle the routes
from django.urls import path
from playroom.views import *

app_name = 'playroom'

# определение маршрутов приложения playroom
# defining the routes of the playroom app
urlpatterns = [
    path('detail/<int:pk>/', TaskDetail.as_view(), name='task_detail'),
    path('<int:topic_id>/', TasksByTopic.as_view(), name='topic'),
    path('', task, name='playroom')
]

pythonposeur/urls.py
"""
pythonposeur URL Configuration
The `urlpatterns` list routes URLs to views. For more information please see:
https://docs.djangoproject.com/en/3.2/topics/http/urls/
"""

# импорт модуля settings + метода static для использования статических файлов во время разработки веб-сайта
# import settings module + static method to use static files during website development
from django.conf import settings
from django.conf.urls.static import static
# импорт пакета приложения admin для использования маршрутов приложения admin
# import the admin app package to use the admin app routes
from django.contrib import admin
# импорт метода path для обработки маршрутов
# import the path method to handle the routes
from django.urls import path, include


# подключение маршрутов приложений
# connecting application routers
urlpatterns = [
    path('admin/', admin.site.urls),                    # администрация сайта; administration page
    path('account/', include('account.urls')),          # приложение account; application account
    path('playroom/', include('playroom.urls')),        # приложение playroom; application playroom
    path('yummypython/', include('yummypython.urls')),  # приложение yummypython; application yummypython
    path('social-auth/', include('social_django.urls', namespace='social')),  # google авторизация; google authorization
    path('martor/', include('martor.urls')),                            # язык разметки markdown
]

# добавление(DEBUG = True) пути к сортировке статических файлов(изображения)
# add(DEBUG = True) path to sort static files(images)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

yummypython/urls.py
from django.urls import path
from yummypython.views import *


app_name = 'yummypython'


urlpatterns = [
    path('detail/<int:pk>/', SubtopicDetail.as_view(), name='subtopic_detail'),
    path('<int:topic_id>/', Subtopics.as_view(), name='subtopics_by_topic'),
    path('', subjects, name='yummypython')
]

playroom/models.py
# импорт пакета models, для определения полей базы данных приложения playroom
# import of the models package, to define the fields of the playroom application database
from django.db import models
# импорт модели базы данных пользователя для установления связи между моделями
# import a user database model to establish a relationship between models
from account.models import Profile
from martor.models import MartorField

# default - присваивает полю значение по умолчанию, если поле явно не определено
# on_delete - предотвращение удаления записи первичной модели, при удалении записи во вторичной модели
# unique — если True, то в текущее поле может быть занесено только уникальное в пределах таблицы значение
# db_index - создание индекса поля


# модель базы данных задач
# database model of tasks
class Task(models.Model):
    topic = models.ForeignKey('Topic', on_delete=models.PROTECT, null=True)  # поле темы
    title = models.CharField(max_length=50, default=True)  # поле названия задачи
    content = MartorField(default=True)                 # поле описания задачи
    difficulty = models.ForeignKey('Difficulty', on_delete=models.PROTECT, null=True)  # поле сложности задачи
    pixels = models.ForeignKey('Pixel', on_delete=models.PROTECT, null=True)  # поле количества балов задачи
    author = models.ForeignKey(Profile, on_delete=models.PROTECT, null=True)   # поле автора задачи

    # настройки модели
    # model settings
    class Meta:
        ordering = ['topic', 'difficulty']

    # строковое представление полей модели
    # string representation of model fields
    def __str__(self):
        return self.title

    # определение ссылки для автора задачи
    # defining a link for the author task
    # def get_absolute_url(self):
    #     return '/account/%s/' % self.author  # <а href="{{ tasks.get_absolute_url }}">{{ tasks.author }}</a>


# модель базы данных тем
# database model of topics
class Topic(models.Model):
    name = models.CharField(max_length=50, default=True, db_index=True, unique=True, verbose_name='topic')

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    # определение ссылки для фильтрации задач относительно тем
    # defining a link to filter tasks relative to topics
    # def get_absolute_url(self):
    #     return '/playroom/%s/' % self.name  # <а href="{{ topic.get_absolute_url }}">{{ topic.name }}</a>


# модель базы данных сложности задачи
# database model of task difficulty
class Difficulty(models.Model):
    name = models.CharField(max_length=50, default=True, verbose_name='difficulty')
    pixels = models.OneToOneField('Pixel', on_delete=models.PROTECT)

    class Meta:
        pass

    def __str__(self):
        return self.name


# модель базы данных балов задачи
# database model of task score
class Pixel(models.Model):
    score = models.IntegerField(default=5, verbose_name='pixels')

    class Meta:
        pass

    def __str__(self):
        return str(self.score)

playroom/views.py
# импорт метода render для формирования ответа пользователю
# import of the render method to form a response to the user
from django.shortcuts import render
# импорт декоратора login_required + LoginRequiredMixin для проверки авторизации пользователя
# import the login_required decorator + LoginRequiredMixin to check user authorization
#from django.contrib.auth.decorators import login_required
#from django.contrib.auth.mixins import LoginRequiredMixin
# импорт объектов для создания представления страниц
# importing objects to create page views
from playroom.models import Task, Topic
from django.views.generic.base import TemplateView
from django.core.paginator import Paginator
from django.views.generic.detail import DetailView


# метод для отправки страницы playroom авторизованному пользователю
# method to send playroom page to authorized user
def task(request):
    tasks = Task.objects.all()
    topics = Topic.objects.all()
    # пагинатор для количества задач на одной странице
    # paginator for amount of tasks on one page
    paginator = Paginator(tasks, 5)
    if 'page' in request.GET:
        page_num = request.GET['page']
    else:
        page_num = 1
    page = paginator.get_page(page_num)
    context = {'topics': topics, 'page': page, 'tasks': page.object_list}
    return render(request, 'playroom/playroom.html', context)


# класс отображения задач относительно темы
# class for displaying tasks relative to the topic
class TasksByTopic(TemplateView):
    template_name = 'playroom/tasks_by_topic.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['topic_tasks'] = Task.objects.filter(topic=context['topic_id'])
        context['topics'] = Topic.objects.all()
        context['current_topic'] = Topic.objects.get(pk=context['topic_id'])
        return context


# контроллер-класс для отображения деталей задачи
# class for displaying details of tasks
class TaskDetail(DetailView):
    model = Task

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['topics'] = Topic.objects.all()
        #context['current_topic'] = Topic.objects.get(pk=context['topic_id'])
        return context

playroom/templates/playroom/playroom.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap5 %}
{% block title %}playroom{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <a class="playroom" href="{% url 'playroom:playroom' %}">>playroom</a>
            <div class="block_topics_6">
                <a class="dellink" href="{% url 'playroom:playroom' %}">
                    <img class="heart1" src="{% static 'images/computer1.gif' %}" height="80px" width="80px">
                </a></br>
                {% for topic in topics %}
                    <a class="topic" href="{% url 'playroom:topic' topic.pk %}">{{ topic.name }}</a><br>
                {% endfor %}
            </div>
        </div>
        <div class="col-6">
            <div class="block_task_6">
                <a class="dellink" href="{% url 'playroom:playroom' %}"><img class="heart1" src="{% static 'images/cat2.gif' %}" height="70px" width="70px"></a><br>
                {% for task in tasks %}
                    <a class="task" href="{% url 'playroom:task_detail' pk=task.pk %}">{{ task.title }}</a><br>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

playroom/templates/playroom/task_detail.html
{% extends "base.html" %}
{% load static %}
{% load martortags %}
{% block css %}
  <link href="{% static 'plugins/css/ace.min.css' %}" type="text/css" media="all" rel="stylesheet"/>
  <link href="{% static 'martor/css/martor.bootstrap.css' %}" type="text/css" media="all" rel="stylesheet"/>
{% endblock %}
{% block title %}{{ task.title }}{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-8">
            <a class="playroom" href="{% url 'playroom:playroom' %}">>playroom</a>
            <div class="martor-preview">
                <p class="detail">>>>{{ task.title }}</p>
                <hr/>
                {{ task.content|safe_markdown }}
                <p class="detail">{{ task.difficulty }}</p>
                <a class="dellink" href="{% url 'yummypython:yummypython'%}">
                    <img class="heart1" src="{% static 'images/light1.gif' %}" height="80px" width="80px">
                </a></br>
            </div>
        </div>
        <div class="col-4">
            <div class="block_topics">
                <a class="dellink" href="{% url 'playroom:task_detail' pk=task.pk%}">
                    <img class="heart1" src="{% static 'images/computer1.gif' %}" height="80px" width="80px">
                </a></br>
                {% for topic in topics %}
                    <a class="topic" href="{% url 'playroom:topic' topic.pk %}">{{ topic.name }}</a>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block js %}
  <script type="text/javascript" src="{% static 'plugins/js/highlight.min.js' %}"></script>
  <script>
    $('.martor-preview pre').each(function(i, block){
        hljs.highlightBlock(block);
    });
  </script>
{% endblock %}

playroom/templates/playroom/tasks_by_topic.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap5 %}
{% block title %}{{ current_topic.name }}{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <a class="playroom" href="{% url 'playroom:playroom' %}">>playroom</a>
            <div class="block_topics_6">
                <a class="dellink" href="{% url 'playroom:topic' current_topic.pk %}">
                    <img class="heart1" src="{% static 'images/computer1.gif' %}" height="80px" width="80px">
                </a></br>
                <a class="currenttopic" href="{% url 'playroom:topic' current_topic.pk %}">>>>{{ current_topic.name }}</a><br>
                {% for topic in topics %}
                    <a class="topic" href="{% url 'playroom:topic' topic.pk %}">{{ topic.name }}</a><br>
                {% endfor %}
            </div>
        </div>
        <div class="col-6">
            <div class="block_task_6">
                <a class="dellink" href="{% url 'playroom:playroom' %}"><img class="heart1" src="{% static 'images/cat2.gif' %}" height="70px" width="70px"></a><br>
                {% for task in topic_tasks %}
                    <a class="task" href="{% url 'playroom:task_detail' pk=task.pk %}">{{ task.title }}</a>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}