account/urls.py
# импорт метода path для определения маршрутов
# import path method to define routes
from django.urls import path
from django.contrib.auth import views as auth_views
# импорт контроллеров для отправки ответа на запрос пользователя
# import controllers to send a response to a user request
from account.views import *


app_name = 'account'

# пути ведущие к страницам относительно заданного шаблона(запроса пользователя)
# paths leading to pages relative to the given template(user request)
urlpatterns = [
    path('delete-user/done/', UserDeleteDone.as_view(), name='delete_user_done'),  # страница успешного удаления пользователя
    path('delete-user/', UserDelete.as_view(), name='delete_user'),  # страница удаления пользователя
    path('password-change/', PasswordChange.as_view(), name='password_change'),  # страница изменения пароля
    path('edit/', UserEdit.as_view(), name='edit'),  # страница редактирования информации пользователя
    path('register/activate/<str:sign>/', user_activate, name='register_activate'),  # страница активации
    path('register/done/', RegisterDone.as_view(), name='register_done'),  # страница успешной регистрации
    path('register/', Register.as_view(), name='register'),  # страница регистрации
    path('password-reset/complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),  # страница успешной смены пароля
    path('password-reset/confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'),
         name='password_reset_confirm'),  # страница смены пароля
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),  # страница об успешном запросе сброса пароля
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html'),
         name='password_reset'),  # страница сброса пароля
    path('login/', Login.as_view(), name='login'),  # страница входа
    path('logout/', Logout.as_view(), name='logout'),  # страница выхода
    path('', Account.as_view(), name='profile'),  # страница профиля пользователя
]

playroom/urls.py
# импорт метода path для обработки маршрутов
# import the path method to handle the routes
from django.urls import path
from playroom.views import *

app_name = 'playroom'

# определение маршрутов приложения playroom
# defining the routes of the playroom app
urlpatterns = [
    path('detail/<int:pk>/', TaskDetail.as_view(), name='task_detail'),
    path('<int:topic_id>/', TasksByTopic.as_view(), name='topic'),
    path('', task, name='playroom')
]

pythonposeur/urls.py
"""
pythonposeur URL Configuration
The `urlpatterns` list routes URLs to views. For more information please see:
https://docs.djangoproject.com/en/3.2/topics/http/urls/
"""

# импорт модуля settings + метода static для использования статических файлов во время разработки веб-сайта
# import settings module + static method to use static files during website development
from django.conf import settings
from django.conf.urls.static import static
# импорт пакета приложения admin для использования маршрутов приложения admin
# import the admin app package to use the admin app routes
from django.contrib import admin
# импорт метода path для обработки маршрутов
# import the path method to handle the routes
from django.urls import path, include


# подключение маршрутов приложений
# connecting application routers
urlpatterns = [
    path('admin/', admin.site.urls),                    # администрация сайта; administration page
    path('account/', include('account.urls')),          # приложение account; application account
    path('playroom/', include('playroom.urls')),        # приложение playroom; application playroom
    path('yummypython/', include('yummypython.urls')),  # приложение yummypython; application yummypython
    path('social-auth/', include('social_django.urls', namespace='social')),  # google авторизация; google authorization
    path('martor/', include('martor.urls')),                            # язык разметки markdown
]

# добавление(DEBUG = True) пути к сортировке статических файлов(изображения)
# add(DEBUG = True) path to sort static files(images)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

yummypython/urls.py
from django.urls import path
from yummypython.views import *


app_name = 'yummypython'


urlpatterns = [
    path('detail/<int:pk>/', SubtopicDetail.as_view(), name='subtopic_detail'),
    path('<int:topic_id>/', Subtopics.as_view(), name='subtopics_by_topic'),
    path('', subjects, name='yummypython')
]

account/models.py
# импорт пакета models, для определения полей базы данных приложения account
# import of the models package, to define the fields of the account application database
from django.db import models
# импорт класса AbstractUser для унаследования полей для базы данных о пользователе
# import of the AbstractUser class to inherit fields for the user database
from django.contrib.auth.models import AbstractUser


# default - значение по умолчанию, записываемое в поле, если в него явно не было занесено никакого значения
# db_index - создание индекса поля
# verbose_name - второе имя поля, которое будет отображаться на страницах веб-сайта
# upload_to - определение директории для загрузки файлов
# blank - позволяет заносить в поле пустое значение, делая поле необезательным к заполнению


# модель базы данных пользователя с унаследованием полей от модели AbstractUser
# user database model with inheritance of fields from AbstractUser model
class Profile(AbstractUser):
    # определение поля активации пользователя после регистрации
    # defining the user activation field after registration
    is_activated = models.BooleanField(default=True, db_index=True, verbose_name='activated')
    # определение поля для фотографии пользователя
    # defining the field for the user's photo
    photo = models.ImageField(upload_to='users/%Y/%m/%d', blank=True)
    pixels = models.IntegerField(default=0)  # поле количества пикселей

    # унаследование настроек класса AbstractUser
    # inherit the settings of the AbstractUser class
    class Meta(AbstractUser.Meta):
        pass

    # строковое представление полей базы данных относительно username
    # string representation of database fields relative to username
    def __str__(self):
        return self.username

    # определение ссылок для задач
    # defining a link to tasks
    # def get_absolute_url(self):
    #      return '/playroom/%s/' % self.username  # <а href="{{ topic.get_absolute_url }}">{{ topic.name }}</a>

account/forms.py
# импорт пакета forms для извлечения полей и унаследования ModelForm
# import forms package to extract fields and inherit ModelForm
from django import forms
# импорт объектов для проверки пароля
# import of objects for password verification
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError
from account.models import Profile
from account.apps import user_registered


# label - надпись для поля
# required - если True, то в поле обязательно должно быть занесено значение
# widget - элемент управления, представляющий текущее поле на веб-странице.


# форма для регистрации пользователя
# user registration form
class UserRegistrationForm(forms.ModelForm):
    email = forms.EmailField(required=True)
    password1 = forms.CharField(label='password', widget=forms.PasswordInput,
                                help_text=password_validation.password_validators_help_text_html())
    password2 = forms.CharField(label='repeat password', widget=forms.PasswordInput)

    # метод clean_password1 для проверки валидности пароля1
    # method clean_password1 to check if password1 is valid
    def clean_password1(self):
        password1 = self.cleaned_data['password1']
        if password1:
            password_validation.validate_password(password1)
        return password1

    # метод clean для проверки равенства двух паролей
    # clean method to check if two passwords are equal
    def clean(self):
        super().clean()
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 and password2 and password1 != password2:
            errors = {'password2': ValidationError("ops! passwords didn't match", code='password_mismatch')}
            raise ValidationError(errors)

    # медот для предварительного сохранения данных о новом пользователе
    # method for pre-saving data about a new user
    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.is_active = False
        user.is_activated = False
        if commit:
            user.save()
        # сигнал для отправки сообщения пользователю с ссылкой активации аккаунта
        # signal to send a message to the user with an account activation link
        user_registered.send(UserRegistrationForm, instance=user)
        return user

    class Meta:
        model = Profile
        fields = ('username', 'email', 'password1', 'password2')


# класс для определения формы редактирования информации пользователя
# class for defining the form for editing user information
class UserEditForm(forms.ModelForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = Profile
        fields = ('username', 'first_name', 'last_name', 'email', 'photo')

account/views.py
# импорт метода render для формирования ответа пользователю
# import of the render method to form a response to the user
from django.shortcuts import render, get_object_or_404
# импорт декоратора login_required + LoginRequiredMixin для проверки авторизации пользователя
# import the login_required decorator + LoginRequiredMixin to check user authorization
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
# импорт объектов для создания представления страниц
# importing objects to create page views
from django.contrib.auth.views import PasswordChangeView, LoginView, LogoutView
from django.views.generic.base import TemplateView
from django.views.generic.edit import DeleteView, CreateView, UpdateView
from django.contrib.auth import logout
from django.core.signing import BadSignature
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from account.forms import UserRegistrationForm, UserEditForm
from account.models import Profile
# иморт экземпляра класса Signer для экономии оперативной памяти
# importing an instance of the Signer class to save RAM
from account.utilities import signer


# класс для отправки страницы входа пользователя на сайт
# class for sending the user login page to the site
class Login(LoginView):
    template_name = 'account/login.html'


# класс для отправки страницы выхода пользователя
# class for sending the user logout page
class Logout(LoginRequiredMixin, LogoutView):
    template_name = 'account/logout.html'


# метод для отправки страницы профиля авторизованному пользователю
# method to send profile page to authorized user
class Account(LoginView):
    template_name = 'account/profile.html'


# класс для представления формы при регистрации пользователя
# class for form submission during user registration
class Register(CreateView):
    model = Profile
    form_class = UserRegistrationForm
    template_name = 'account/register.html'
    success_url = reverse_lazy('account:register_done')


# класс для уведомления об успешной регистрации пользователя
# class for notification of successful user registration
class RegisterDone(TemplateView):
    template_name = 'account/register_done.html'


# метод для подтверждения активации
# method to confirm activation
def user_activate(request, sign):
    try:
        username = signer.unsign(sign)
    except BadSignature:
        return render(request, 'account/bad_signature.html')
    user = get_object_or_404(Profile, username=username)
    if user.is_activated:
        template = 'account/user_is_activated.html'
    else:
        template = 'account/activation_done.html'
        user.is_active = True
        user.is_activated = True
        user.save()
    return render(request, template)


# класс представления формы для редактирования информации о пользователе
# form submission class for editing user information
class UserEdit(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Profile
    form_class = UserEditForm
    template_name = 'account/edit.html'
    success_url = reverse_lazy('account:profile')
    success_message = 'yami! profile updated successfully'

    # метод получения индекса пользователя в базе данных
    # method for getting the user's index in the database
    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)

    # метод извлечения исправляемого поля
    # method to retrieve the field to be corrected
    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


# класс для изменения пароля пользователя
# class for changing user password
class PasswordChange(LoginRequiredMixin, SuccessMessageMixin, PasswordChangeView):
    template_name = 'account/password_change.html'
    success_url = reverse_lazy('account:profile')
    success_message = 'password changed'


# класс для удаления пользователя
# class for deleting a user
class UserDelete(LoginRequiredMixin, DeleteView):
    model = Profile
    template_name = 'account/delete_user.html'
    success_url = reverse_lazy('account:delete_user_done')

    # сохранение индекса пользователя
    # save user index
    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)

    # предварительный выход из аккаунта перед удалением пользователя
    # preliminary log out of the account before deleting the user
    def post(self, request, *args, **kwargs):
        logout(request)
        return super().post(request, *args, **kwargs)

    # метод поиска пользователя
    # user search method
    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


# класс для уведомления об успешном удалении пользователя
# class for notification of successful user deletion
class UserDeleteDone(TemplateView):
    template_name = 'account/delete_user_done.html'

account/templates/base.html
<!DOCTYPE html>
<html>
    {% load static %}
    {% load bootstrap5 %}
    <head>
        <meta charset="UTF-8">
        <link rel="icon" href="{% static 'images/heart1(32x32).png' %}" sizes="32x32">
        <link rel="stylesheet" href="{% static 'account/base.css' %}">
        <link rel="stylesheet" href="{% static 'account/bootstrap-grid.css' %}">
        <title>{% block title %}python poseur{% endblock %}</title>
    </head>
    <body>
      <div class="container">
        <div class="row">
          <div class="col">
            <div class="block_login_logout">
              {% if request.user.is_authenticated %}
                <a class="loglink" href="{% url 'account:logout' %}">logout?</a><br>
                <a class="loglink" href="{% url 'yummypython:yummypython' %}"><img class="heart1" src="{% static 'images/pythonlogo1.png' %}" height="70px" width="70px"></a>
                <a class="loglink" href="{% url 'yummypython:yummypython' %}"><img class="heart1" src="{% static 'images/snake2.png' %}" height="70px" width="70px"></a>
              {% else %}
                <a class="loglink" href="{% url 'account:login' %}">login</a><br>
                <a class="loglinkgoogle" href="{% url 'social:begin' 'google-oauth2' %}"><img class="rainbow1" src="{% static 'images/google3.gif' %}" height="65px" width="150px"></a>
              {% endif %}
            </div>
          </div>
          <div class="col">
            {% if messages %}
              {% for message in messages %}
                <p class="{{ message.tags }}">{{ message }} <a href="{% url 'account:profile' %}" class="{{ message.tags }}">✖</a></p>
              {% endfor %}
            {% endif %}
          </div>
          <div class="col">
            <div class="block_user">
              {% if request.user.is_authenticated %}
                {% if request.user.photo %}
                  <a href="{% url 'account:profile' %}"><img class="usericon1" src="{{ request.user.photo.url }}" height="65px" width="65px"></a>
                {% else %}
                  <a href="{% url 'account:profile' %}"><img class="icon1" src="{% static 'images/heart1.png' %}" height="65px" width="65px"></a>
                {% endif %}
                <a class="reglink" href="{% url 'account:profile' %}">
                  {% if request.user.first_name %}
                    {{ request.user.first_name }}
                  {% else %}
                    {{ request.user.username }}
                  {% endif %}
                </a><br>
                <a class="pixels">0=pixels</a>
              {% else %}
                <a href="{% url 'account:login' %}"><img class="icon1" src="{% static 'images/heart3.gif' %}" height="65px" width="65px"></a>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-12">
            <div class="menu">
              <button onclick="myFunction()" class="menubtn">map</button>
              <div id="mymenu" class="menu-content">
                <a class="m1" href="{% url 'account:profile' %}">profile</a>
                <a class="m2" href="{% url 'playroom:playroom' %}">playroom</a>
                <a class="m2" href="{% url 'yummypython:yummypython' %}">yummypython</a>
                <a class="m3" href="#">about</a>
              </div>
            </div><br>
          </div>
        </div>
      </div>
      <script>
            function myFunction() {
                document.getElementById("mymenu").classList.toggle("show");
            }
          
            window.onclick = function(event) {
              if (!event.target.matches('.menubtn')) {
            
                var dropdowns = document.getElementsByClassName("menu-content");
                var i;
                for (i = 0; i < dropdowns.length; i++) {
                  var openDropdown = dropdowns[i];
                  if (openDropdown.classList.contains('show')) {
                    openDropdown.classList.remove('show');
                  }
                }
              }
            }
      </script>
      {% block content %}
      {% endblock %}
    </body>
</html>

account/templates/new_base.html
<!DOCTYPE html>
<html>
    {% load static %}
    {% load martortags %}
    <head>
        <meta charset="UTF-8">
        <link rel="icon" href="{% static 'images/heart1(32x32).png' %}" sizes="32x32">
        <link type="text/css" rel="stylesheet" media="all" href="{% static 'account/base_light.css' %}" id="theme-link">
        <link rel="stylesheet" href="{% static 'account/bootstrap-grid.css' %}">
        {% block css %}
        {% endblock %}
        <title>{% block title %}python poseur{% endblock %}</title>
    </head>
    <body>
      <div class="container">
        <div class="row">
          <div class="col">
            <div class="block_login_logout">
              {% if request.user.is_authenticated %}
                <a class="logout1" href="{% url 'account:logout' %}">logout?</a><br>
                <a class="login1" href="{% url 'yummypython:yummypython' %}"><img class="heart1" src="{% static 'images/pythonlogo1.png' %}" height="70px" width="70px"></a>
                <a class="login1" href="{% url 'yummypython:yummypython' %}"><img class="heart1" src="{% static 'images/snake2.png' %}" height="70px" width="70px"></a>
              {% else %}
                <a class="login1" href="{% url 'account:login' %}">login</a><br>
                <a class="logingoogle1" href="{% url 'social:begin' 'google-oauth2' %}"><img class="rainbow1" src="{% static 'images/google3.gif' %}" height="65px" width="150px"></a>
              {% endif %}
            </div>
          </div>
          <div class="col">
            <div class="block_msg_theme">
              {% if messages %}
              {% for message in messages %}
                <p class="{{ message.tags }}">{{ message }} <a href="{% url 'account:profile' %}" class="{{ message.tags }}">✖</a></p><br>
              {% endfor %}
              {% endif %}
              <button class="theme-button" id="switchTheme">partymode</button>
              <a href="https://en.wikipedia.org/wiki/Spider-Man" target='_blank'><img class="heart1" src="{% static 'images/spudik3.gif' %}" height="70px" width="90px"></a>
            </div>
          </div>
          <div class="col">
            <div class="block_user">
              {% if request.user.is_authenticated %}
                {% if request.user.photo %}
                  <a href="{% url 'account:profile' %}"><img class="usericon1" src="{{ request.user.photo.url }}" height="65px" width="65px"></a>
                {% else %}
                  <a href="{% url 'account:profile' %}"><img class="icon1" src="{% static 'images/heart1.png' %}" height="65px" width="65px"></a>
                {% endif %}
                <a class="userlink1" href="{% url 'account:profile' %}">
                  {% if request.user.first_name %}
                    {{ request.user.first_name }}
                  {% else %}
                    {{ request.user.username }}
                  {% endif %}
                </a><br>
              {% else %}
                <a href="{% url 'account:login' %}"><img class="icon1" src="{% static 'images/heart3.gif' %}" height="65px" width="65px"></a>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-12">
            <div class="menu">
              <button onclick="menuButtom()" class="menubtn">map</button>
              <div id="mymenu" class="menu-content">
                <a class="m1" href="{% url 'account:profile' %}">profile</a>
                <a class="m2" href="{% url 'playroom:playroom' %}">playroom</a>
                <a class="m2" href="{% url 'yummypython:yummypython' %}">yummypython</a>
                <a class="m3" href="#">about</a>
              </div>
            </div><br>
          </div>
        </div>
      </div>
      <script>
            function menuButtom() {
                document.getElementById("mymenu").classList.toggle("show");
            }
          
            window.onclick = function(event) {
              if (!event.target.matches('.menubtn')) {
            
                var dropdowns = document.getElementsByClassName("menu-content");
                var i;
                for (i = 0; i < dropdowns.length; i++) {
                  var openDropdown = dropdowns[i];
                  if (openDropdown.classList.contains('show')) {
                    openDropdown.classList.remove('show');
                  }
                }
              }
            }
      </script>
      <script type="text/javascript">
        if (!localStorage.theme) localStorage.theme = 'light'
        document.body.className = localStorage.theme

        switchTheme.onclick = () => {
          document.body.classList.toggle('dark');
          switchTheme.innerText = document.body.classList.contains('dark') ? 'lightparty' : 'darkparty';
          localStorage.theme = document.body.className || 'light'
        }
      </script>
      {% block js %}
      {% endblock %}
      {% block content %}
      {% endblock %}
      <a href="https://en.wikipedia.org/wiki/Spider-Man" target="_blank"><img class="spudik2" src="{% static 'images/spudik2.gif' %}" height="90px" width="90px"></a>
    </body>
</html>