account/urls.py
# импорт метода path для определения маршрутов
# import path method to define routes
from django.urls import path
from django.contrib.auth import views as auth_views
# импорт контроллеров для отправки ответа на запрос пользователя
# import controllers to send a response to a user request
from account.views import *


app_name = 'account'

# пути ведущие к страницам относительно заданного шаблона(запроса пользователя)
# paths leading to pages relative to the given template(user request)
urlpatterns = [
    path('delete-user/done/', UserDeleteDone.as_view(), name='delete_user_done'),  # страница успешного удаления пользователя
    path('delete-user/', UserDelete.as_view(), name='delete_user'),  # страница удаления пользователя
    path('password-change/', PasswordChange.as_view(), name='password_change'),  # страница изменения пароля
    path('edit/', UserEdit.as_view(), name='edit'),  # страница редактирования информации пользователя
    path('register/activate/<str:sign>/', user_activate, name='register_activate'),  # страница активации
    path('register/done/', RegisterDone.as_view(), name='register_done'),  # страница успешной регистрации
    path('register/', Register.as_view(), name='register'),  # страница регистрации
    path('password-reset/complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),  # страница успешной смены пароля
    path('password-reset/confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'),
         name='password_reset_confirm'),  # страница смены пароля
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),  # страница об успешном запросе сброса пароля
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html'),
         name='password_reset'),  # страница сброса пароля
    path('login/', Login.as_view(), name='login'),  # страница входа
    path('logout/', Logout.as_view(), name='logout'),  # страница выхода
    path('', Account.as_view(), name='profile'),  # страница профиля пользователя
]

pythonposeur/urls.py
"""
pythonposeur URL Configuration
The `urlpatterns` list routes URLs to views. For more information please see:
https://docs.djangoproject.com/en/3.2/topics/http/urls/
"""

# импорт модуля settings + метода static для использования статических файлов во время разработки веб-сайта
# import settings module + static method to use static files during website development
from django.conf import settings
from django.conf.urls.static import static
# импорт пакета приложения admin для использования маршрутов приложения admin
# import the admin app package to use the admin app routes
from django.contrib import admin
# импорт метода path для обработки маршрутов
# import the path method to handle the routes
from django.urls import path, include


# подключение маршрутов приложений
# connecting application routers
urlpatterns = [
    path('admin/', admin.site.urls),                    # администрация сайта; administration page
    path('account/', include('account.urls')),          # приложение account; application account
    path('playroom/', include('playroom.urls')),        # приложение playroom; application playroom
    path('yummypython/', include('yummypython.urls')),  # приложение yummypython; application yummypython
    path('social-auth/', include('social_django.urls', namespace='social')),  # google авторизация; google authorization
    path('martor/', include('martor.urls')),                            # язык разметки markdown
]

# добавление(DEBUG = True) пути к сортировке статических файлов(изображения)
# add(DEBUG = True) path to sort static files(images)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

yummypython/urls.py
from django.urls import path
from yummypython.views import *


app_name = 'yummypython'


urlpatterns = [
    path('detail/<int:pk>/', SubtopicDetail.as_view(), name='subtopic_detail'),
    path('<int:topic_id>/', Subtopics.as_view(), name='subtopics_by_topic'),
    path('', subjects, name='yummypython')
]

yummypython/models.py
# импорт пакета models для наследования от объекта Model
# import the models package to inherit from the Model object
from django.db import models
# импорт объекта Markdown для определение содержимого поля content
# import a Markdown object to define the content of the content field
from martor.models import MartorField


# определение базы данных подтем
# define the subtopics database
class Subtopic(models.Model):
    name = models.CharField(max_length=50, default=True, verbose_name='subtopic')
    content = MartorField(default=True)
    topic = models.ForeignKey('Topic', on_delete=models.PROTECT, default=True)

    class Meta:
        pass

    def __str__(self):
        return self.name


# определение быза данных основных тем
# defining a database of main topics
class Topic(models.Model):
    name = models.CharField(max_length=50, default=True, db_index=True, unique=True, verbose_name='topic')

    class Meta:
        pass

    def __str__(self):
        return self.name

yummypython/views.py
from django.shortcuts import render
from django.views.generic.detail import DetailView
from django.views.generic.base import TemplateView
from yummypython.models import *


# отображение всех тем
def subjects(request):
    topics = Topic.objects.all()
    context = {'topics': topics}
    return render(request, 'yummypython/yummypython.html', context)


# отображение подтем, относительно выбранной темы
class Subtopics(TemplateView):
    template_name = 'yummypython/subtopics_by_topic.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['subtopics'] = Subtopic.objects.filter(topic=context['topic_id'])
        context['topics'] = Topic.objects.all()
        context['current_topic'] = Topic.objects.get(pk=context['topic_id'])
        return context


# отображение деталей подтемы
class SubtopicDetail(DetailView):
    model = Subtopic

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['topics'] = Topic.objects.all()
        # context['current_subtopic'] = Subtopic.objects.get(pk=context['topic_id'])
        return context


# отображение страницы информации о проекте
class About(TemplateView):
    template_name = 'account/about.html'

yummypython/templates/yummypython/subtopic_detail.html
{% extends "base.html" %}
{% load static %}
{% load martortags %}
{% block css %}
  <link href="{% static 'plugins/css/ace.min.css' %}" type="text/css" media="all" rel="stylesheet" />
  <link href="{% static 'martor/css/martor.bootstrap.css' %}" type="text/css" media="all" rel="stylesheet" />
{% endblock %}
{% block title %}{{ subtopic.name }}{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-9">
            <a class="yummypython" href="{% url 'yummypython:yummypython' %}">>yummypython</a>
            <div class="martor-preview">
                <p class="detail">>>>{{ subtopic.topic }}</p>
                <hr>
                {{ subtopic.content|safe_markdown }}
            </div>
        </div>
        <div class="col-3">
            <div class="block_topics_3">
                <a class="dellink" href="{% url 'yummypython:subtopic_detail' pk=subtopic.pk %}">
                    <img class="heart1" src="{% static 'images/light1.gif' %}" height="70px" width="70px">
                </a></br>
                {% for topic in topics %}
                    <a class="topic" href="{% url 'yummypython:subtopics_by_topic' topic.pk %}">{{ topic.name }}</a><br>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block js %}
  <script type="text/javascript" src="{% static 'plugins/js/highlight.min.js' %}"></script>
  <script>
    $('.martor-preview pre').each(function(i, block){
        hljs.highlightBlock(block);
    });
  </script>
{% endblock %}

yummypython/templates/yummypython/subtopics_by_topic.html
{% extends "base.html" %}
{% load static %}
{% block title %}{{ current_topic.name }}{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <a class="yummypython" href="{% url 'yummypython:yummypython' %}">>yummypython</a>
            <div class="block_topics_6">
                <a class="dellink" href="{% url 'yummypython:subtopics_by_topic' current_topic.pk %}">
                    <img class="heart1" src="{% static 'images/light1.gif' %}" height="70px" width="70px">
                </a></br>
                <a class="currenttopic" href="{% url 'yummypython:subtopics_by_topic' current_topic.pk %}">>>>{{ current_topic.name }}</a><br>
                {% for topic in topics %}
                    <a class="topic" href="{% url 'yummypython:subtopics_by_topic' topic.pk %}">{{ topic.name }}</a><br>
                {% endfor %}
            </div>
        </div>
        <div class="col-6">
            <div class="block_subtopics">
                <a class="dellink" href="{% url 'yummypython:subtopics_by_topic' current_topic.pk %}">
                    <img class="heart1" src="{% static 'images/computer1.gif' %}" height="80px" width="80px">
                </a></br>
                {% for subtopic in subtopics %}
                    <a class="topic" href="{% url 'yummypython:subtopic_detail' pk=subtopic.pk %}">{{ subtopic.name }}</a><br>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

yummypython/templates/yummypython/yummypython.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap5 %}
{% block title %}yummy python{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <a class="yummypython" href="{% url 'yummypython:yummypython' %}">>yummypython</a>
            <div class="block_topics_12">
                <a class="dellink" href="{% url 'yummypython:yummypython' %}">
                    <img class="heart1" src="{% static 'images/light1.gif' %}" height="80px" width="80px">
                </a></br>
                {% for topic in topics %}
                    <a class="topic" href="{% url 'yummypython:subtopics_by_topic' topic.pk %}">{{ topic.name }}</a><br>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}